#!/usr/bin/env python
# Generated by BigMap 2 - https://github.com/zverik/bigmap2 - Permalink: http://bigmap.osmz.ru/bigmap.php?xmin=3548&xmax=3585&ymin=1630&ymax=1653&zoom=12&scale=256&tiles=landscape
# Customized by orneh24 for https://github.com/orneh24/shikoku88map4print
# Using a 512x512 pixel OpenStreepMap tileserver, will produce a 38912 x 24576 pixel (~550-600 MB depending on tiles used) .png and a ~100 MB .jpeg map designed for A0 printing with some cutting of the edges. Fun fact, that resolution is a total of 956.301.312 pixels.

import io, urllib.request, datetime, time, re, random
from PIL import Image, ImageDraw, ImageFont
# ^^^^^^ install "python-pillow" package | pip install Pillow | easy_install Pillow

(zoom, xmin, ymin, xmax, ymax) = (13, 7096, 3260, 7171, 3307)

layers = ["https://tile.openstreetmap.org/!z/!x/!y.png", "https://tile.waymarkedtrails.org/hiking/!z/!x/!y.png"]
tilesize = 256
# demo version, using the official OpenStreepMap default tile, combined with waymarkedtrails.org hiking route
# For a list of tile servers, both free and paid, see https://wiki.openstreetmap.org/wiki/Raster_tile_providers
# customized tileset as displayed in Github repo - requires API key from Maptiler (free account can view map, but subscription required to use XYZ downloads
# layers = ["https://api.maptiler.com/maps/d13bb37e-ea9c-41d1-933e-4e36c785a0bf/!z/!x/!y.png?key=YOUR-API-KEY-HERE"]
attribution = 'https://github.com/orneh24/shikoku88map4print \n© OpenMapTiles.org - http://openmaptiles.org - © OpenStreetMap contributors'
attrfont = ImageFont.truetype('Roboto-Black.ttf', 250)
xsize = xmax - xmin + 1
ysize = ymax - ymin + 1

resultImage = Image.new("RGBA", (xsize * tilesize, ysize * tilesize), (0,0,0,0))
counter = 0
for x in range(xmin, xmax+1):
	for y in range(ymin, ymax+1):
		for layer in layers:
			url = layer.replace("!x", str(x)).replace("!y", str(y)).replace("!z", str(zoom))
			match = re.search("{([a-z0-9]+)}", url)
			if match:
				url = url.replace(match.group(0), random.choice(match.group(1)))
			print(url, "... ");
			try:
				req = urllib.request.Request(url, headers={'User-Agent': 'BigMap/2.0'})
				tile = urllib.request.urlopen(req).read()
			except Exception as e:
				print("Error", e)
				continue;
			image = Image.open(io.BytesIO(tile))
			resultImage.paste(image, ((x-xmin)*tilesize, (y-ymin)*tilesize), image.convert("RGBA"))
			counter += 1
			if counter == 20:
				time.sleep(2);
				counter = 0

# Add attribution text
draw = ImageDraw.Draw(resultImage)
draw.text((22816, 23740), attribution, (0,0,0), font=attrfont)

# Add a 252x252 px grid to map (2km across)
y_start = 0
y_end = resultImage.height
step_size = 252
for x in range(0, resultImage.width, step_size):
        line = ((x, y_start), (x, y_end))
        draw.line(line, fill=0)
        x_start = 0
        x_end = resultImage.width

for y in range(0, resultImage.height, step_size):
        line = ((x_start, y), (x_end, y))
        draw.line(line, fill=0)

del draw

scaleimage = Image.open("scale_100km.png")
# Create a mask from the alpha channel of the km scale image
_, _, _, mask = scaleimage .split()
# Paste the km scale image onto the new image with the mask
resultImage.paste(scaleimage , (22932, 21650), mask)
resultImage = resultImage.convert("RGB")
now = datetime.datetime.now()
outputFileName = "shikoku88map4print-%02d-%02d%02d%02d-%02d%02d.png" % (zoom, now.year % 100, now.month, now.day, now.hour, now.minute)
resultImage.save(outputFileName)
# Temp output jpeg file
outputFileNameTemp = "shikoku88map4print-%02d-%02d%02d%02d-%02d%02d.jpeg" % (zoom, now.year % 100, now.month, now.day, now.hour, now.minute)
resultImage.save(outputFileNameTemp)